### ISSUE TITLE
Batch correction, use of labels, and pre-processing to align populations

### ISSUE THREAD

**Issue by dr-michael-haley** [shuxiaoc/maxfuse#13]
Hi,

I am adapting your second tutorial to integrate IMC data with scRNAseq.

Do you have any advice for incorporating batch correction, particularly when working with protein data (specifically, IMC)? We commonly use BBKNN or Harmony through Scanpy, though since these compensate at the neighbours or PCA stages, they do not affect the raw values that are provided to MaxFuse. However, any labels provided will have been generated on the batch corrected labels, so I assume that will provide some degree of batch correction during the smooth steps? Theoretically, we could use a batch correction method that adjusts the raw data (e.g. Combat)...

Secondly, does it matter if the labels do not match between the modalities? I realise if the names are the same it will make it easier to interpret the accuracy of the matching (e.g. using the ConfusionMatrix), but does it otherwise impact the matching?

Should the labels be matched as closely as possible between modalities in terms of how specific the labels are? For example, 'T cells' in one dataset, and 'CD4 T-cells', 'CD8 T-cells' in another.

How do you handle populations which are going to be undetectable in one of your datasets? For example, we may not have markers in our panel to identify some populations in the tissue, but they will appear in the scRNAseq dataset.

Thanks for creating such an amazing tool, it's really impressive and a huge step forward from previous attempts!

**Comment by BokaiZhu** [comment]
Hi,

Thanks for your interest in the method!

Question 1 about batch correction: Yes, this is indeed a very important point. The raw counts will not be affected, but only the clustering labels will be affected. As you described, if labels are generated from batch-corrected embeddings, they provide some level of smoothing. Also, the batch-corrected embeddings can be used in the refined-matching step as 'features,' which can provide additional 'batch-smoothing' to the matching results. For example, in our Hubmap tri-modality integration, we have used harmony-corrected PCs (e.g., scATAC-LSI) as input for refined matching. As you mentioned, raw values can be 'corrected' and used during initial matching. This could theoretically work, but we have not tested this comprehensively.

Question 2, Do the labels need to be matched? No, it is not required. The matching labels in our manuscript are only for benchmarking reasons (e.g., to calculate confusion matrices). For actual running, the labels do not need to be name-matched.

Question 3, How do we handle missing cell types? If the missing cell types are not known when running the matching, the method itself handles this issue to some degree (e.g., filtering out the low-quality matching cells, likely due to no matching in the other modality). However, if missing cell types are 'prior knowledge,' it would be best practice to remove them from matching. We think that in scenarios where good matching is not possible for these cells, it would be natural to remove them from our matching tasks.

Please let me know if this clarification makes sense and if you have any additional questions!

Best,
Bokai

**Comment by BokaiZhu** [comment]
Hi Im closing this issue since it has been a while, but please do feel free to reopen if there is any followup questions!

Best,
Bokai

**Comment by kuang-da** [comment]
Hi, love the tool and the manuscript! Thank you for creating it!

Based on the following step in the analysis notebook, it seems the author uses the Harmony latent space as the transition to correct the raw counts
![Image](https://github.com/user-attachments/assets/49fc7c06-622d-45cb-b0a1-16e0687309e1)

However, this is probably not the one used for the manuscript because it does not align with Bokai's comment about Question 1. I wonder if there is any example script we could use as a reference to handle multiple-batch cases (ideally for scRNA-seq). Thank you very much!

**Comment by BokaiZhu** [comment]
Sorry for the confusion. The reply in Q1 with '_For example, in our Hubmap tri-modality integration, we have used harmony-corrected PCs (e.g., scATAC-LSI) as input for refined matching._' was exactly referring to the code snippet you are showing here, and it is the process we used in our manuscript. Let me know if you have questions regarding that and I can help clarify. We have not tried multiple-batches but I think this process should work (using harmony PC to recontruct corrected raw counts).

**Comment by kuang-da** [comment]
Thank you for the prompt reply! I am trying to create a cross-modal benchmark, and I feel like MaxFuse is a great tool to set up the connections across modality. In general, I am okay to follow the tutorial and codebase to build my pipeline, but I am a bit hesitant to use Harmony PC to generate corrected counts because it has been discouraged by its developer.

https://github.com/immunogenomics/harmony/issues/102

Would love to hear your insights about this with-modality integration step. Thank you!

**Comment by BokaiZhu** [comment]
Yes, I agree with you on being cautious about using harmony to 'correct' the actual count values, and that is the reason we confined the usage of it only during the second round matching (not in initial matching), and such values are also not used in any downstream analysis for actual biology discovery. Unfortunately, I think that is the best way I can think of (without overtly complicating matters), in the context of achieving cell matching with MaxFuse during the step of refined matching. Happy to hear you insight on this too, as it is indeed a lightly explored area in spatial (especially proteomics).

**Comment by kuang-da** [comment]
Thanks for providing more details. It is probably okay since the corrected counts are used for matching, as you said. 

Thank you!
